### ISSUE TITLE
Add link to hackclub.com

### ISSUE THREAD

**Issue by lachlanjc** [mason-hack-club/mason-hack-club.github.io#3]
Hey friends, quick favor here. We're trying to improve SEO for hackclub.com and we only have 14 links from other sites. Could you add a link somewhere on your site to ours?

Thanks :)

**Comment by cravend** [comment]
Already have one! "a chapter of the international [Hack Club organization](https://hackclub.com/)" on the homepage.

**Comment by lachlanjc** [comment]
🙈 thanks dalton :)
